version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
  basketcache:
    image: redis:alpine
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  catalogdb:
    image: mongo:latest
  mongoclient:
    image: mongoclient/mongoclient
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
volumes:
  mongo_data:
  portainer_data: